# Generated by Django 3.2.9 on 2021-12-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='resumen',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
