# Generated by Django 3.2.9 on 2021-12-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuario_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='resumen',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
