# Generated by Django 3.2.9 on 2021-12-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20211215_0007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogcategoria',
            table='blog_categoria',
        ),
    ]
