# Generated by Django 3.2.9 on 2021-12-16 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0005_auto_20211215_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomentario',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogcomentario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcomentario',
            name='nombre',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
