# Generated by Django 3.2.9 on 2021-12-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_blogcomentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(blank=True, default='https://archive.org/download/placeholder-image/placeholder-image.jpg', null=True, upload_to=''),
        ),
    ]
