# Generated by Django 3.2.9 on 2021-12-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_blogpost_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to=''),
        ),
    ]
