# Generated by Django 3.2.9 on 2022-01-10 23:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0018_alter_blogcomentario_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
