# Generated by Django 3.2.9 on 2021-12-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogcomentario',
            table='blog_comentario',
        ),
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_post',
        ),
    ]
