# Generated by Django 3.2.9 on 2021-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogcategoria_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
