# Generated by Django 3.2.9 on 2021-12-18 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0007_auto_20211217_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('contenido', models.TextField(max_length=500)),
                ('publicado', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Blog.blogpost')),
            ],
            options={
                'db_table': 'blog_comentario',
                'ordering': ('-publicado',),
            },
        ),
    ]
