# Generated by Django 3.2.9 on 2022-01-07 02:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_blogpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomentario',
            name='contenido',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
