# Generated by Django 3.2.9 on 2022-01-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_auto_20220106_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomentario',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
