# Generated by Django 3.2.9 on 2022-01-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_blogpost_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='like',
            new_name='likes',
        ),
    ]
